name: PushJobs

on:
  push:
    branches: 
      - main


jobs:
  phpstan:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        -name: Setup PHP
         uses: shivammathur/setup-php@v2
          with:
            php-version: '8.3' # or any other PHP version you are using
            extensions: mbstring, intl, pdo_mysql # add any other extensions you need
            coverage: none

          
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse database public storage --memory-limit 300M